#!/bin/sh

# Set these paths appropriately

BIN=/Applications/TreeTagger/bin
CMD=/Applications/TreeTagger/cmd
LIB=/Applications/TreeTagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian-utf8.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
